### PR TITLE
Creates Travis config and ESLint runner

### LINKED ISSUE #176: Add a lint runner to automatically run a linter check to every PR that is created.

### PR DESCRIPTION
**Pull request by shaneriley**
Fixes #176

**Description**

Creates a Travis CI config file to run ESLint on any non-node_modules JS file in the repo. Reports failure in TravisCI console and passes a pass/fail message back to GitHub for rendering.

**Technical**

We may want to have a discussion on either limiting the linting to particular packages or to instead completely disable the checks on a per-file basis.

**Testing**

If you'd like, you can branch off of this one, make a commit, and push. Travis CI will run ESLint and display the results on https://travis-ci.com/internetarchive/iaux

**Evidence**

Screen Shot 2019-06-17 at 2 49 04 PM

### CODE REVIEW

**Comment by iisa** [comment]
@shaneriley this bubbles up the conversation of what are the next steps to make this light up green.  I am thinking 2 approaches:
1) we should lint files and PR into this master branch
2) have a conversation about the ESLint rules that we need to change.

What are your thoughts?

**Comment by shaneriley** [comment]
I think that works. I've kind of been waiting until we know Mitra's work is complete, but instead we could add ignores in his section for the time being.

**Comment by mitra42** [comment]
We definitely need to either discuss the rules, or add the ignores.
I keep finding myself UNDOing changes made by ESLint which make the code less readable, especially when you've got JSX and JS mixed up.

**Comment by shaneriley** [comment]
I definitely do not want to employ an autocorrecting linter solution, as I'm sure I'll fight with it on every commit as well. I think having the warnings and errors reported in Travis instead allows us to address them in the syntax we feel is most appropriate and if we feel an override is necessary, we can add it on a per line or per file basis.

**Comment by mitra42** [comment]
Per file makes sense, but per-line lint exceptions just make the code even more unreadable as they just put these exceptions in the file !

**Comment by iisa** [comment]
hi @shaneriley ok if we close this?

**Comment by shaneriley** [comment]
Do you mean close without merging?

**Pull request closed without merging**
