### PR TITLE
Migrate Babel from version 6 to version 7

### PR DESCRIPTION
**Pull request by shreyansh23**
**Description**
Migrate Babel from version 6 to version 7
For more information see PR #22

### CODE REVIEW

**Comment by shreyansh23** [comment]
@iisa 
Can you please add this to the project board in the "To Do" or "Review in process" category?

**Comment by iisa** [comment]
@shreyansh23 just wanted to sync on GH about our talk.  Will this PR be affected with the Storybook and/or Jest upgrade?

**Comment by shreyansh23** [comment]
@iisa 
Only Babel migration is handled by this. 
After this the changes will

**Comment by iisa** [comment]
hey @shreyansh23 when you get back to working on this, let's do a PR for each package, that way we can isolate where babel needs the upgrades. and it will be an easier task to complete.

**Comment by iisa** [comment]
closing because this is split up. lmk if I am wrong @shreyansh23

**Pull request closed without merging**
