### PR TITLE
[WIP]Create a Sandbox section for audioplayers

### PR DESCRIPTION
**Pull request by Batey96**
creates a new section just for audio players and their related files

### CODE REVIEW

**Comment by Batey96** [comment]
This PR isolates a sandbox for audio players..Every consumer of this sandbox is updated of its new path location

**Comment by iisa** [comment]
@Batey96 can you make the description section more robust? it will be easier to make your case with screenshots, etc. also, it looks like there is conflict, please do resolve

**Comment by iisa** [comment]
@Batey96  i like where this is going. 👍 
keep this new directory: `./sandbox/audio-players`
add these players: `audio-player-main`, `archive-audio-jwplayer-wrapper`, `third-party-embed` so they are siblings in that new directory.

then, add the rest of the files in the same directory: `audio-player.less/.stories.js/.test.js`
At this point all the files should be all siblings in the new directory that you created
- commit at this point

THEN, update the references for these files where they are used.  then commit at this point.

THEN, extend the `audio-player.stories.js` file to include examples of the new stories.  then commit at this point.
Please do provide screenshots of the new stories and a screenshot of the current audio theatre with youtube & spotify all working.

Looking forward to this! 😃

**Comment by Batey96** [comment]
Hi thanks for all your corrections..will work on all.First by relablling and adding a WIP status as recommended by you

**Comment by iisa** [comment]
resolved with #519

**Pull request closed without merging**
