### PR TITLE
Move fsevents to optional dependencies in package.json

### PR DESCRIPTION
**Pull request by shreyansh23**
Related to #16 

The package "fsevents" was in written in dependencies in package.json `ia-components`. But that package is only compatible for macOS.

Ref: https://medium.com/@satawneh/npm-install-error-fsevents-in-ohter-mac-platforms-953101fc2797

Because of this error was coming on `yarn install` on Linux operating systems.

After this PR all installation steps will work correctly for macOS as well as for Linux.

### CODE REVIEW

**Comment by shreyansh23** [comment]
No @Batey96 
I didn't get the following that errors. Can you please pull my changes and then try the exact instruction mentioned in README.md.
I am pretty sure that you will not get any problem.

**Comment by shreyansh23** [comment]
> @shreyansh23 yes let's update all the babel versions in the other repos to stay in parity. would you also check if we actually need @fsevents in `ia-components`?

Okay @iisa 
I am upgrading all the babel packages.

**Comment by shreyansh23** [comment]
Got closed by mistake. Please see #22 .

**Comment by mitra42** [comment]
Careful with Babel - it seems that none of us really understand it, and there are incompatibilities with what you have to include in what config files (babel.rc and webpack.config) for different versions.  I have a complete mess in the IAUX2 branch of dweb-archive and cannot find any combination of babel that will run properly with webpack and also at runtime. On Friday @iisa and I got it compiling with up to date babel, but it complained about a runtime missing - adding the runtime meant it wouldn't compile.

**Comment by mitra42** [comment]
If you want to try this .... 
Check out [dweb-mirror](https://github.com/internetarchive/dweb-mirror)#iaux2 and checkout [iaux](https://github.com/internetarchive/iaux)#dwebnew. They should be in side-by-side directories (e.g. `git/dweb-mirror` and `git/iaux` ). Then try `cd dweb-mirror && webpack --mode development`.  I cannot get it to webpack except by removing some things, in particular `plugin-transform-runtime` and it seems to need one of those plugins to run in the browser (Its not clear if its `babel-plugin-transform-runtime` or `@babel/plugin-transform-runtime`). 

Note - you'll probably need to do `cd dweb-mirror && yarn install` and also maybe `cd dweb-mirror && ./install.sh` before webpack-ing. 

If you figured out how to get this to work it would be huge.

**Pull request closed without merging**
