### PR TITLE
Fix `ia-component` Tests

### PR DESCRIPTION
**Pull request by jbuckner**
**Description**

> Fix failing tests in ia-components

**Technical**

> We weren't running the storybook server when running the tests so they were all failing right off the bat.

**Testing**

> Check out this branch, run yarn bootstrap in `packages/ia-components`. Then run `yarn test`

**Evidence**

> n/a

### CODE REVIEW

**Comment by bfalling** [comment]
The code LGTM

**Comment by iisa** [comment]
@jbuckner @shaneriley - would we be able to fix this error by reducing coverage threshold? https://travis-ci.com/internetarchive/iaux/builds/136246784

The trace seems to look good otherwise.

**Comment by jbuckner** [comment]
@iisa Yeah we could do that! I _thought_ I had gotten them all up above 80%.. let me see if there's a branch somewhere with the rest of the tests. Otherwise I'll just lower it and we can raise increase test coverage later. 

I'd like to get this in so we can start running tests regularly.

**Comment by jbuckner** [comment]
@iisa I merged in the other branches to get the test coverage up so that's been taken care of, but now I'm seeing a test fail _only_ when run on Travis CI. It has to do with audio playback so I have a feeling the headless chrome that runs in Travis might not be able to do audio. I'll look into it.

**Comment by jbuckner** [comment]
Tests are fixed 🎉

**Pull request merged**
