### PR TITLE
New package: mobile-top-nav

### PR DESCRIPTION
**Pull request by iisa**
**Description**
Moving top nav to new location.
#312 - please see acceptance notes in main issue.

**Technical**
This component will now be ready to be a stand-alone package.

**Testing**

Pull branch > run `npm install` 
To run Storybook: run `npm run storybook`
To run Demo app (openwc): run `npm run start`

### CODE REVIEW

**Comment by jbuckner** [comment]
This looks good! 💪

**Comment by iisa** [comment]
> This looks good! 💪

ok sounds good. we will forge forth

**Comment by iisa** [comment]
@koderjoker would you be able to help make the demo file &/or stories work inside the new directory? I moved most of the files into the new folder.  I left a few just for reference.

**Comment by iisa** [comment]
@koderjoker this is the final piece for directory migration.  Please do take a look at this, and try it out.  If you see any issue with regards to directory structure - includig any component behavioral issues, please feel free to create commits.  If good to go, do merge to master.

Let's get this in as soon as we can.  I will be working on new tasks off of this branch.

**Pull request merged**
