### PR TITLE
Mitra 353 namingrefactor

### PR DESCRIPTION
**Pull request by mitra42**
**Description**

Mostly this is part of a massive refactor of dweb handling of names and urls - few bug fixes in there as well, as I was debugging the naming.

**Technical**

**Testing**

Its live on dweb.archive.org in conjunction with mitra-352-musicplayer 

**Evidence**

### CODE REVIEW

**Comment by iisa** [comment]
@mitra42 looks like there are conflicts. i pushed in the first MR that was outstanding.  Would you be able to rebase and then we can get this into masteR?

**Comment by mitra42** [comment]
It might make more sense for me to merge master into my current code and push that, since some changes since this PR were related to bug fixes etc with this code.

**Comment by mitra42** [comment]
Ok - I did that.

**Comment by iisa** [comment]
closing this in favor of #354 - @mitra42 please re-open if necessary.

**Pull request closed without merging**
